Repository vindi/vindi-woocommerce-subscriptions, pull requests merged in 2018-07, with the labels that each got.

#88 Cria CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: preciso de ajuda :raising_hand:

#86 Atualiza CONTRIBUTING.md
  CONTRIBUTING.md
Labels: preciso de ajuda :raising_hand:

#85 Adição da Transação de Verificação
  includes/class-vindi-api.php
  includes/class-vindi-creditcard-gateway.php
  includes/class-vindi-payment.php
Labels: melhoria :dancer:

#89 Atualiza README
  README.md
Labels: melhoria :dancer:, preciso de ajuda :raising_hand:

#92 Atualiza CHANGELOG.md
  CHANGELOG.md
Labels: melhoria :dancer:, preciso de ajuda :raising_hand:

#91 Atualiza readme.txt
  readme.txt
Labels: melhoria :dancer:, preciso de ajuda :raising_hand:
